// Code generated by "stringer -type=DebugControl -linecomment"; DO NOT EDIT.

package lisp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DebugNoop-0]
	_ = x[DebugStepOver-1]
	_ = x[DebugStepInto-2]
	_ = x[DebugStepOut-3]
	_ = x[DebugContinue-4]
	_ = x[DebugExit-5]
}

const _DebugControl_name = "DebugNoopDebugStepOverDebugStepIntoDebugStepOutDebugContinueDebugExit"

var _DebugControl_index = [...]uint8{0, 9, 22, 35, 47, 60, 69}

func (i DebugControl) String() string {
	if i < 0 || i >= DebugControl(len(_DebugControl_index)-1) {
		return "DebugControl(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DebugControl_name[_DebugControl_index[i]:_DebugControl_index[i+1]]
}
