package printer

import (
	"fmt"
	"math/big"
	"reflect"
	"runtime"
	"strconv"
	"strings"
	"time"

	"github.com/jig/lisp/marshaler"
	"github.com/jig/lisp/types"
)

// Pr_list implements pr-list Lisp function
func Pr_list(lst []types.MalType, pr bool,
	start string, end string, join string) string {
	str_list := make([]string, 0, len(lst))
	for _, e := range lst {
		str_list = append(str_list, Pr_str(e, pr))
	}
	return start + strings.Join(str_list, join) + end
}

// Pr_str converts an AST to a string, suitable for printing
// AST might be generated by lisp.EVAL(...) or by lisp.READ(...) or lisp.READWithPreamble(...).
func Pr_str(obj types.MalType, print_readably bool) string {
	switch tobj := obj.(type) {
	case int:
		return strconv.Itoa(tobj)
	case int8, int16, int32, int64,
		uint, uint8, uint16, uint32, uint64:
		return fmt.Sprintf("%d", tobj)
	case time.Time:
		return fmt.Sprintf("%d", tobj.UnixMilli())
	case time.Duration:
		return fmt.Sprintf("%d", tobj.Milliseconds())
	case *big.Int:
		if tobj == nil {
			return "nil"
		}
		return bigIntToHex(tobj)
	case types.LispPrintable:
		return tobj.LispPrint(Pr_str)
	case types.List:
		return Pr_list(tobj.Val, print_readably, "(", ")", " ")
	case types.Vector:
		return Pr_list(tobj.Val, print_readably, "[", "]", " ")
	case marshaler.HashMap:
		value, err := tobj.MarshalHashMap()
		if err != nil {
			return "{}"
		}
		return hashMapToString(value.(types.HashMap), print_readably)
	case types.HashMap:
		return hashMapToString(tobj, print_readably)
	case types.Set:
		str_list := make([]string, 0, len(tobj.Val))
		for k := range tobj.Val {
			str_list = append(str_list, Pr_str(k, print_readably))
		}
		return "#{" + strings.Join(str_list, " ") + "}"
	case string:
		if strings.HasPrefix(tobj, "\u029e") {
			return ":" + tobj[2:]
		} else if print_readably {
			if strings.HasPrefix(tobj, `{"`) && strings.HasSuffix(tobj, `}`) {
				return `¬` + strings.Replace(tobj, `¬`, `¬¬`, -1) + `¬`
			} else {
				return `"` + strings.Replace(
					strings.Replace(
						strings.Replace(tobj, `\`, `\\`, -1),
						`"`, `\"`, -1),
					"\n", `\n`, -1) + `"`
			}
		} else {
			return tobj
		}
	case types.Symbol:
		return tobj.Val
	case nil:
		return "nil"
	case types.MalFunc:
		return "(fn " +
			Pr_str(tobj.Params, true) + " " +
			Pr_str(tobj.Exp, true) + ")"
	case types.Func:
		return fmt.Sprintf("«function %v»", strings.ToLower(runtime.FuncForPC(reflect.ValueOf(tobj.Fn).Pointer()).Name()))
	case func([]types.MalType) (types.MalType, error):
		return fmt.Sprintf("«function %v»", obj)
	case error:
		return "«go-error " + Pr_str(tobj.Error(), true) + "»"
	case fmt.Stringer:
		// Honour fmt.Stringer so Go values carrying a custom String()
		// render meaningfully instead of exposing their internal struct
		// layout. This must come before the pointer dereference below, as
		// many Stringer methods use pointer receivers and would otherwise
		// be lost on indirection.
		//
		// Guard a nil pointer receiver first: the default branch below
		// renders any nil pointer as "nil", but reaching String() here
		// short-circuits that, and a String() that dereferences its
		// receiver would panic. Keep the safe "nil" rendering.
		if v := reflect.ValueOf(tobj); v.Kind() == reflect.Pointer && v.IsNil() {
			return "nil"
		}
		return tobj.String()
	default:
		if v := reflect.ValueOf(obj); v.Kind() == reflect.Pointer {
			// if the value is a pointer, dereference it to print the value instead of the address
			if v.IsNil() {
				return "nil"
			}
			return Pr_str(reflect.Indirect(v).Interface(), print_readably)
		}
		return fmt.Sprintf("%v", obj)
	}
}

// bigIntToHex formats a big.Int the way the reader accepts it back: a
// 0x-prefixed uppercase hex literal, zero-padded to whole octets (e.g.
// "0x0A1B2C", zero is "0x00") with a leading "-" for negatives, so big
// ints round-trip through print and read.
func bigIntToHex(i *big.Int) string {
	b := i.Bytes()
	if len(b) == 0 {
		b = []byte{0}
	}
	s := fmt.Sprintf("0x%X", b)
	if i.Sign() < 0 {
		return "-" + s
	}
	return s
}

func hashMapToString(tobj types.HashMap, print_readably bool) string {
	str_list := make([]string, 0, len(tobj.Val)*2)
	for k, v := range tobj.Val {
		str_list = append(str_list, Pr_str(k, print_readably))
		str_list = append(str_list, Pr_str(v, print_readably))
	}
	return "{" + strings.Join(str_list, " ") + "}"
}
